title: Shaemless
description: AE-E --- RIDE DEEP
baseurl: ""
url: "https://shaemless.github.io"

collections:
  events:
    output: true
    permalink: /events/:name/

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event

markdown: kramdown
